const Employer_portal_link = 'https://employer.jobanya.com';
const bestjobs_link = 'mailto:support@jobanya.com';
const fb_link = 'https://www.facebook.com/jobanya.official';
const insta_link = 'https://www.instagram.com/jobanya_official/?igshid=YmMyMTA2M2Y=';
const linkedin_link = 'https://twitter.com/BestJobsapp/';
const twitter_link = 'https://twitter.com/BestJobsapp/';
const youtube_link = 'https://www.youtube.com/channel/UCXTknuz12ghgr9RGn-ObPBA';
const telegram_emp_link = 'https://web.telegram.org/z/#-1421753823';
const telegram_emplr_link = 'https://web.telegram.org/z/#-1453088242';
const abuse_employee = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/abuse_employee.jpg';
const abuse_employer = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/abuse_employer.jpg';
const accept_employee = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/accept_employee.jpg';
const apply_job = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/apply_job.png';
const approve_employer = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/approve_employer.jpg';
const approve_jobpost = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/approve_jobpost.jpg';
//const bestjobs_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/bestjobs_logo.jpg';
const bestjobs_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/Jobanya_logo.jpg';
const change_emailid = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/change_emailid.png';
const employee_feedback = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/employee_feedback.jpg';
const employer_feedback = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/employer_feedback.jpg';
const expiring_subscription = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/expiring_subscription.jpg';
const fb_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/fb_logo.jpg';
const forgot_password = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/forgot_password.jpg';
const insta_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/insta_logo.jpg';
const linkedin_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/linkedin_logo.jpg';
const promo_code = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/promo_code.jpg';
const reject_employer = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/reject_employer.jpg';
const reject_jobpost = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/reject_jobpost.jpg';
const save_jobpost = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/save_jobpost.png';
const success_subscription = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/success_subscription.jpg';
const twitter_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/twitter_logo.jpg';
const verification_mail = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/verification_mail.png';
const welcome_mail = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/welcome_mail.png';
const youtube_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/youtube_logo.jpg';
const telegram_logo = 'https://bj-email-template.s3.ap-south-1.amazonaws.com/telegram_logo.jpg';
module.exports = Object.freeze({telegram_emp_link,telegram_emplr_link,telegram_logo,abuse_employee,abuse_employer,accept_employee,apply_job,approve_employer,approve_jobpost,bestjobs_logo,change_emailid,employee_feedback,employer_feedback,expiring_subscription,fb_logo,forgot_password,insta_logo,linkedin_logo,promo_code,reject_employer,reject_jobpost,
    save_jobpost,success_subscription,twitter_logo,verification_mail,
    welcome_mail,youtube_logo,bestjobs_link,fb_link,insta_link,linkedin_link,twitter_link,youtube_link,Employer_portal_link});